### ISSUE TITLE
Request for unofficial clarification

### ISSUE THREAD

**Issue by tagawa** [thth/duckduckgo_top_result#1]
Hi. Thanks for making this add-on to help people use DuckDuckGo more easily.

Unfortunately we (DuckDuckGo) sometimes hear about users being confused about what's an official add-on and what isn't. To avoid this confusion, please could you:

- Change the logo so it doesn't feature the "Dax the duck" mascot,
- Make it clear your usage is "unofficial" in the description?

Thanks in advance.

**Comment by thth** [comment]
@tagawa Sorry about the trouble! I can certainly see how my add-on can cause confusion and have addressed the logo and description.

For the [description](https://addons.mozilla.org/en-US/firefox/addon/duckduckgo-top-result/), I've added the preamble:

> This is an unofficial DuckDuckGo search engine add-on for going to the top result. For the official DuckDuckGo search engine add-on with regular functionality, go [here](https://addons.mozilla.org/en-US/firefox/addon/duckduckgo-for-firefox/). 

As for the logo, to inform users that my add-on is, while not an official DuckDuckGo extension, still related to DuckDuckGo, I've replaced it with an icon of a dashingly handsome Australian duck, who, while similar to Dax, surely cannot be mistaken for him:

![duckduckgo96](https://user-images.githubusercontent.com/7574985/74096416-a40ae400-4ab3-11ea-9a8b-4b5683f02926.png)

If, however, you fear that this Australian duck is **too** dashingly handsome and might steal the spotlight away from Dax, please inform me so and I will gladly replace our Australian friend and maybe also enjoy a Peking Duck dinner.

❤️ 🦆

**Comment by tagawa** [comment]
Hi again. No need to apologise!

Thank you for making the changes so quickly, however I fear the dashing handsomeness is indeed a bit too high with the Australian version. If it helps, a site I use for free icons is OpenClipArt (no usage restrictions). They don't seem to have the search feature enabled at the moment but it should be possible through DuckDuckGo, e.g.:
https://duckduckgo.com/?q=duck+site%3Aopenclipart.org&iax=images&ia=images

Perhaps there's something suitable in there?

**Comment by thth** [comment]
I got another duck. Definitely less handsome.

![duckduckgo96](https://user-images.githubusercontent.com/7574985/74297236-1c171b00-4cfb-11ea-8451-d1293a0b05f5.png)

**Comment by tagawa** [comment]
I dunno, I'd still trade places for those looks!

Anyway, thanks again for the quick action.

I'd love to send you a t-shirt as a small token of thanks. If you'd like that, please send me an email at daniel at duckduckgo dot com
