### ISSUE TITLE
This doesn't work?

### ISSUE THREAD

**Issue by Bandit** [thth/duckduckgo_top_result#2]
Just takes me to https://html.duckduckgo.com/html/

**Comment by e-t-l** [comment]
I'm experiencing the same issue. Not sure if something changed on DDG's backend, as this extension hasn't been updated for months. @thth Any ideas?

EDIT: I uninstalled and reinstalled the extension, and it appears to work now. @Bandit give it a shot?

**Comment by thth** [comment]
DuckDuckGo changed their search url, requiring `https://html.duckduckgo.com/html/` instead of `https://duckduckgo.com/html/`. I did end up fixing the search extension ~3 days after the change (21 days ago), so version 1.3 should be working.

Sorry for the late comment!
